# Generated by Django 4.1.2 on 2022-10-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('productId', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateTimeField()),
            ],
        ),
    ]
